version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "gh actions"
    open-pull-requests-limit: 1
    cooldown:
      default-days: 5
      semver-major-days: 21
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      minor-and-patch-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "gradle"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 5
      semver-major-days: 21
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      minor-and-patch-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
