version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "gh actions"
    open-pull-requests-limit: 1
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "gradle"
    open-pull-requests-limit: 10
